### ISSUE TITLE
:bug: Compatibility issues

### ISSUE THREAD

**Issue by ximlu** [chris-araman/AsyncCloudKit#11]
Is this library no longer maintained? I encountered some issues when using it on the latest Xcode 15. For example, the compilation error when calling `func accountStatus()` and the warning about `Sendable`. I hope you can update it to be compatible with the latest Xcode version.

**Comment by malhal** [comment]
I don't know if it is still maintained but there is now a built-in async version of `accountStatus()` in Xcode 15's CloudKit framework.

**Comment by chris-araman** [comment]
I am unfortunately unable to maintain this project moving forward. If you would like to fork and maintain it, please reach out.
